# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Website Draft
email: blank@blank.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#MISC config
timezone: America/New_York

sbcs-facebook: https://www.facebook.com/groups/sb.computing/
sbcs-google-calendar: http://google.com
sbcs-slack: http://seawolf.com
sbcs-email: sbucomputingsociety@gmail.com

# Force include Jekyll to dynamically input variables created by 
include: ['_src']


# Configure Sass file directory
# sass:
#   sass_dir: _sass
#   style: compressed

#Colors
lightgray: '#CCC'
darkgray: "#CCC"
white: '#000'
red: 'red'
blue: 'blue'

sm-width: 1
md-width: 2
footer-xs-height: 1
footer-sm-height: 1